"""Streamlit dashboard for the Rapido mobility insights project.

Run with:
    streamlit run app/streamlit_app.py

Expects data/processed/final_merged_data.csv and the four models in
models/ to already exist (run the src/ pipeline first - see README.md).
"""

import json

import joblib
import pandas as pd
import streamlit as st

CATEGORICAL_COLORS = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#4a3aa7"]

PREDICTION_LEAK_COLUMNS = [
    "ride_status", "ride_outcome_target", "cancelled_by",
    "customer_cancel_flag", "driver_delay_flag",
    "booking_id", "customer_id", "driver_id", "booking_time",
]

st.set_page_config(page_title="Rapido Mobility Insights", layout="wide")


@st.cache_data
def load_data():
    return pd.read_csv("data/processed/final_merged_data.csv")


@st.cache_resource
def load_models():
    return {
        "ride_outcome": joblib.load("models/ride_outcome_model.pkl"),
        "ride_outcome_encoder": joblib.load("models/ride_outcome_label_encoder.pkl"),
        "fare": joblib.load("models/fare_model.pkl"),
        "customer_cancel": joblib.load("models/customer_cancel_model.pkl"),
        "driver_delay": joblib.load("models/driver_delay_model.pkl"),
    }


@st.cache_data
def load_metrics():
    try:
        with open("reports/model_metrics.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return None


def build_template_row(df, overrides):
    """Starts from a real booking (so every column the models expect is
    present with a sensible value) and overwrites just the fields the user
    actually controls in the UI - far less fragile than hand-typing a
    50-column dict that has to be kept in sync with feature_engineering.py
    by hand every time a feature is added or renamed."""
    row = df.iloc[[0]].copy()
    for col, value in overrides.items():
        row[col] = value
    return row


def prepare_for_prediction(row, extra_drop=None):
    drop_cols = list(PREDICTION_LEAK_COLUMNS) + list(extra_drop or [])
    return row.drop(columns=[c for c in drop_cols if c in row.columns])


try:
    df = load_data()
    models = load_models()
except FileNotFoundError as exc:
    st.error(f"Missing a required file: {exc}")
    st.error("Run the pipeline first: data_cleaning.py -> feature_engineering.py -> train_model.py")
    st.stop()

metrics = load_metrics()

st.title("Rapido: Intelligent Mobility Insights")

page = st.sidebar.selectbox(
    "Select Page",
    ["Dashboard", "EDA", "Ride Outcome Prediction", "Fare Prediction",
     "Customer Cancellation Risk", "Driver Delay Risk"],
)

if page == "Dashboard":
    st.subheader("Overview")
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Rides", f"{len(df):,}")
    col2.metric("Completed Rides", f"{int((df['ride_status'] == 'Completed').sum()):,}")
    col3.metric("Cancellation Rate", f"{(df['ride_status'].eq('Cancelled').mean() * 100):.1f}%")

    st.subheader("Ride Volume by Hour")
    st.line_chart(df.groupby("hour").size())

    st.subheader("Ride Status Distribution")
    st.bar_chart(df["ride_status"].value_counts())

    if metrics:
        st.subheader("Model Performance (from reports/model_metrics.json)")
        cols = st.columns(4)
        for col, m in zip(cols, metrics):
            with col:
                if m["task"] == "classification":
                    st.metric(m["model"], f"{m['accuracy']:.1%}", "accuracy")
                    st.caption(f"AUC: {m['auc']:.3f}" if m["auc"] is not None else "AUC: n/a")
                else:
                    st.metric(m["model"], f"{m['rmse']:.2f}", "RMSE")
                    st.caption(f"{m['rmse_pct_of_mean']:.1%} of mean fare, R2={m['r2']:.3f}")
                st.caption("✅ meets benchmark" if m["meets_benchmark"] else "⚠️ below benchmark")
    else:
        st.info("Run `python src/train_model.py` to generate a model performance summary.")

elif page == "EDA":
    st.subheader("Explore Data")
    st.caption("A written EDA report with saved charts is at reports/EDA_REPORT.md "
               "(generated by src/eda.py) - this page is for quick interactive filtering.")
    city = st.selectbox("Select city", sorted(df["city"].dropna().unique()))
    filtered = df[df["city"] == city]

    st.write("Filtered rows:", len(filtered))
    col1, col2, col3 = st.columns(3)
    col1.bar_chart(filtered.groupby("hour").size())
    col2.bar_chart(filtered["vehicle_type"].value_counts())
    col3.bar_chart(filtered["payment_method"].value_counts())

elif page == "Ride Outcome Prediction":
    st.subheader("Predict Ride Outcome")

    col1, col2 = st.columns(2)
    with col1:
        city = st.selectbox("City", sorted(df["city"].dropna().unique()))
        vehicle_type = st.selectbox("Vehicle Type", sorted(df["vehicle_type"].dropna().unique()))
        distance_km = st.number_input("Distance (km)", 0.5, 50.0, 6.0)
        trip_duration_min = st.number_input("Trip Duration (min)", 1.0, 180.0, 20.0)
        traffic_level = st.selectbox("Traffic", ["Low", "Medium", "High"])
        weather_condition = st.selectbox("Weather", ["Clear", "Cloudy", "Rain", "Smog"])
    with col2:
        hour = st.slider("Hour", 0, 23, 9)
        is_weekend = st.selectbox("Weekend?", [0, 1])
        customer_cancellation_rate = st.slider("Customer's historical cancellation rate", 0.0, 1.0, 0.08)
        driver_reliability_score = st.slider("Driver reliability score", 0.0, 100.0, 80.0)
        surge_multiplier = st.number_input("Surge Multiplier", 1.0, 3.0, 1.2)

    if st.button("Predict Ride Outcome"):
        row = build_template_row(df, {
            "city": city, "vehicle_type": vehicle_type, "distance_km": distance_km,
            "trip_duration_min": trip_duration_min, "traffic_level": traffic_level,
            "weather_condition": weather_condition, "hour": hour, "is_weekend": is_weekend,
            "is_peak_hour": int(hour in (7, 8, 9, 17, 18, 19)),
            "rush_hour_flag": int(hour in (7, 8, 9, 17, 18, 19)),
            "customer_cancellation_rate": customer_cancellation_rate,
            "driver_reliability_score": driver_reliability_score,
            "surge_multiplier": surge_multiplier,
        })
        input_df = prepare_for_prediction(row)
        pred = models["ride_outcome"].predict(input_df)
        label = models["ride_outcome_encoder"].inverse_transform(pred)[0]
        st.success(f"Predicted Ride Outcome: **{label}**")

elif page == "Fare Prediction":
    st.subheader("Predict Fare")

    distance_km = st.number_input("Distance (km)", 0.5, 50.0, 6.0)
    trip_duration_min = st.number_input("Trip Duration (min)", 1.0, 180.0, 20.0)
    vehicle_type = st.selectbox("Vehicle Type", sorted(df["vehicle_type"].dropna().unique()))
    base_fare = st.number_input("Base Fare", 20.0, 1000.0, 100.0)
    surge_multiplier = st.number_input("Surge Multiplier", 1.0, 3.0, 1.2)

    if st.button("Predict Fare"):
        row = build_template_row(df, {
            "distance_km": distance_km, "trip_duration_min": trip_duration_min,
            "vehicle_type": vehicle_type, "base_fare": base_fare,
            "surge_multiplier": surge_multiplier,
            "fare_per_km": (base_fare * surge_multiplier) / max(distance_km, 0.1),
            "fare_per_min": (base_fare * surge_multiplier) / max(trip_duration_min, 1),
        })
        input_df = prepare_for_prediction(row, extra_drop=["estimated_fare"])
        pred = models["fare"].predict(input_df)[0]
        st.success(f"Estimated Fare: Rs {pred:.2f}")

elif page == "Customer Cancellation Risk":
    st.subheader("Customer Cancellation Risk")

    total_completed = st.number_input("Completed Rides", 0, 1000, 30)
    total_cancelled = st.number_input("Cancelled Rides", 0, 200, 5)
    customer_rating = st.number_input("Customer Rating", 1.0, 5.0, 4.0)
    traffic_level = st.selectbox("Current Traffic", ["Low", "Medium", "High"])
    weather_condition = st.selectbox("Current Weather", ["Clear", "Cloudy", "Rain", "Smog"])

    if st.button("Predict Customer Risk"):
        cancel_rate = total_cancelled / max(total_completed + total_cancelled, 1)
        row = build_template_row(df, {
            "total_completed_rides": total_completed,
            "total_cancelled_rides": total_cancelled,
            "customer_rating": customer_rating,
            "customer_cancellation_rate": cancel_rate,
            "traffic_level": traffic_level,
            "weather_condition": weather_condition,
        })
        input_df = prepare_for_prediction(row)
        pred = models["customer_cancel"].predict(input_df)[0]
        proba = models["customer_cancel"].predict_proba(input_df)[0][1]
        if pred == 1:
            st.warning(f"High chance of customer cancellation (probability: {proba:.1%})")
        else:
            st.success(f"Low chance of customer cancellation (probability: {proba:.1%})")

elif page == "Driver Delay Risk":
    st.subheader("Driver Delay Risk")
    st.caption("Predicts whether a driver is likely to cause a delay of 10+ minutes on this trip.")

    driver_rating = st.number_input("Driver Rating", 1.0, 5.0, 4.3)
    acceptance_rate = st.slider("Driver Acceptance Rate", 0.0, 1.0, 0.90)
    avg_delay_min = st.number_input("Driver's Average Past Delay (min)", 0.0, 60.0, 5.0)
    traffic_level = st.selectbox("Current Traffic", ["Low", "Medium", "High"])

    if st.button("Predict Driver Delay Risk"):
        row = build_template_row(df, {
            "driver_rating": driver_rating,
            "acceptance_rate": acceptance_rate,
            "avg_delay_min": avg_delay_min,
            "traffic_level": traffic_level,
            "driver_reliability_score": (driver_rating * 20) * 0.4 + (acceptance_rate * 100) * 0.4
                                        + ((1 / (1 + avg_delay_min)) * 100) * 0.2,
        })
        input_df = prepare_for_prediction(row, extra_drop=["driver_delay_min"])
        pred = models["driver_delay"].predict(input_df)[0]
        proba = models["driver_delay"].predict_proba(input_df)[0][1]
        if pred == 1:
            st.warning(f"High risk of driver-caused delay (probability: {proba:.1%})")
        else:
            st.success(f"Low risk of driver-caused delay (probability: {proba:.1%})")
